language: php
php:
- 5.6
- 7.0
- 7.1
before_script:
- composer install
script: phpunit --coverage-text
notifications:
  slack:
    secure: dtCEbnISh0tdlKl6eXcdDNwK7y0cgIg3V4lnrpanzSosj1ZbO9LKsnW5hh3q2+LLL8PTxjJurQKm4GwM+aOUiNveGCLUgn4sDYkubILPHxykYcGTRvXEFHaEx57nZXLibF3yMYni3BPp5/vcK6Duy7FHb5wL+HRQqlPX6XE3k90=
